name: Release

# This workflow will be triggered whenever the CI workflow is triggered in main branch is completed or a release is published
on:
  release:
    types: [ published ]

jobs:
  publish-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: before publish
        run: echo "step before publishing"
      - name: publish
        if: github.repository == 'sanjanag/cicd-test' && github.event_name == 'release' && github.event.action == 'published'
        run : echo "Running publish action"
  commit:
    needs: [ publish-test ]
    if: needs.publish.result == 'success'
    runs-on: "ubuntu-latest"
    steps:
      - name: create file
        run: touch dummy.txt
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: dummy commit